spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/payflow}
    username: ${DB_USER:payflow}
    password: ${DB_PASSWORD:payflow_local}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
